use serde::{Deserialize, Serialize};
use serde_json::Value;

/// A single turn in a conversation between a user, an assistant, and tools.
///
/// The conversation history passed to [`CompletionRequest`](crate::client::request::CompletionRequest)
/// is a `Vec<Message>`. The ordering of variants mirrors the natural flow:
/// `User` → `Assistant` (possibly interleaved with `Thought` / `ToolCall` / `ToolOutput`).
#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum Message {
    /// A message from the human side of the conversation.
    ///
    User { content: String },

    /// A message generated by the assistant (model output).
    ///
    Assistant { content: String },

    /// An internal reasoning step produced by the model (e.g. chain-of-thought).
    ///
    /// Thought messages are not shown to the end user but may be included in
    /// the history for models that support extended thinking.
    Thought { content: String },

    /// A request from the assistant to invoke a tool.
    ///
    /// `call_id` ties this call to the corresponding [`ToolOutput`](Message::ToolOutput).
    ToolCall {
        arguments: String,
        call_id: String,
        name: String,
    },

    /// The result returned by a tool after execution.
    ///
    /// `call_id` must match the [`ToolCall`](Message::ToolCall) that triggered the execution.
    ToolOutput {
        call_id: String,
        output: Value,
        name: String,
    },
}

impl Message {
    pub fn user(content: impl Into<String>) -> Self {
        Message::User {
            content: content.into(),
        }
    }

    pub fn assistant(content: impl Into<String>) -> Self {
        Message::Assistant {
            content: content.into(),
        }
    }

    pub fn thought(content: impl Into<String>) -> Self {
        Message::Thought {
            content: content.into(),
        }
    }

    pub fn is_user(&self) -> bool {
        matches!(self, Message::User { .. })
    }

    pub fn is_assistant(&self) -> bool {
        matches!(self, Message::Assistant { .. })
    }

    pub fn content(&self) -> Option<&str> {
        match self {
            Message::User { content } => Some(content),
            Message::Assistant { content } => Some(content),
            Message::Thought { content } => Some(content),
            _ => None,
        }
    }
}

pub trait MessageVecExt {
    fn last_user_content(&self) -> Option<&str>;
    fn user_messages(&self) -> Vec<&Message>;
    fn without_thoughts(&self) -> Vec<&Message>;
}

impl MessageVecExt for Vec<Message> {
    fn last_user_content(&self) -> Option<&str> {
        self.iter().rev().find_map(|m| match m {
            Message::User { content } => Some(content.as_str()),
            _ => None,
        })
    }

    fn user_messages(&self) -> Vec<&Message> {
        self.iter().filter(|m| m.is_user()).collect()
    }

    fn without_thoughts(&self) -> Vec<&Message> {
        self.iter()
            .filter(|m| !matches!(m, Message::Thought { .. }))
            .collect()
    }
}
