use serde::{Deserialize, Serialize};
use serde_json::Value;

/// A single turn in a conversation between a user, an assistant, and tools.
///
/// The conversation history passed to [`CompletionRequest`](crate::client::request::CompletionRequest)
/// is a `Vec<Message>`. The ordering of variants mirrors the natural flow:
/// `User` → `Assistant` (possibly interleaved with `Thought` / `ToolCall` / `ToolOutput`).
#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum Message {
    /// A message from the human side of the conversation.
    ///
    /// `response_id` links this turn to a prior assistant response when the
    /// provider requires it for context threading.
    User {
        content: String,
        response_id: Option<String>,
    },

    /// A message generated by the assistant (model output).
    ///
    /// `response_id` is the opaque identifier returned by the provider and
    /// should be echoed back in subsequent `User` turns if required.
    Assistant {
        content: String,
        response_id: Option<String>,
    },

    /// An internal reasoning step produced by the model (e.g. chain-of-thought).
    ///
    /// Thought messages are not shown to the end user but may be included in
    /// the history for models that support extended thinking.
    Thought { content: String },

    /// A request from the assistant to invoke a tool.
    ///
    /// `call_id` ties this call to the corresponding [`ToolOutput`](Message::ToolOutput).
    ToolCall {
        arguments: String,
        call_id: String,
        name: String,
    },

    /// The result returned by a tool after execution.
    ///
    /// `call_id` must match the [`ToolCall`](Message::ToolCall) that triggered the execution.
    ToolOutput {
        call_id: String,
        output: Value,
        name: String,
    },
}
