use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::client::tools::ToolCallRequest;

/// The complete, non-streaming response from a completion call.
#[derive(Debug, Clone)]
pub struct CompletionResponse {

    pub id: String,
    /// Provider-specific model identifier that generated the response.
    pub model: String,
    /// Opaque identifier assigned by the provider for this response.
    pub response_id: String,
    /// Ordered list of content blocks produced by the model.
    pub contents: Vec<CompletionResponseContent>,
    /// Token accounting for this response.
    pub usage: CompletionResponseTokenUsage,
}

/// A single content block within a [`CompletionResponse`].
#[derive(Debug, Clone)]
pub enum CompletionResponseContent {
    /// Visible text generated by the model.
    Text(String),
    /// Internal chain-of-thought produced before the visible answer.
    Thought(String),
    /// A request from the model to invoke a tool.
    ToolCall(ToolCallRequest),
}


impl CompletionResponse {
    pub fn text(&self) -> Option<&str> {
        self.contents.iter().find_map(|c| match c {
            CompletionResponseContent::Text(val) => Some(val.as_str()),
            _ => None,
        })
    }

    pub fn text_or_default(&self) -> String {
        let content = self.contents.iter().find_map(|c| match c {
            CompletionResponseContent::Text(val) => Some(val.as_str()),
            _ => None,
        });
        content.unwrap_or_default().to_string()
    }

}


#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CompletionResponseTokenUsage {
    /// Total "Fresh" or "Standard" input tokens sent.
    pub input_tokens: i32,

    /// Tokens read from a cache (OpenAI's cached_tokens or Anthropic's cache_read).
    /// These are a subset of your total input context but usually billed cheaper.
    pub cached_read_tokens: i32,

    /// Tokens written to the prompt cache during this call (billed at write rate).
    pub cached_write_tokens: i32,

    /// Tokens used specifically for tool definitions or results overhead.
    pub tool_use_tokens: i32,

    /// Internal "thinking" tokens (OpenAI Reasoning / Gemini Thoughts).
    /// Note: These are almost always billed as 'Output' tokens.
    pub reasoning_tokens: i32,

    /// The visible text tokens generated by the model.
    pub output_tokens: i32,

    /// The grand total (Input + Output + Reasoning).
    pub total_tokens: i32,
}

impl std::ops::AddAssign for CompletionResponseTokenUsage {
    fn add_assign(&mut self, rhs: Self) {
        self.input_tokens += rhs.input_tokens;
        self.cached_read_tokens += rhs.cached_read_tokens;
        self.cached_write_tokens += rhs.cached_write_tokens;
        self.tool_use_tokens += rhs.tool_use_tokens;
        self.reasoning_tokens += rhs.reasoning_tokens;
        self.output_tokens += rhs.output_tokens;
        self.total_tokens += rhs.total_tokens;
    }
}

/// A single chunk delivered by a streaming completion call.
///
/// Chunks arrive incrementally as the model generates output. When `is_final`
/// is `true` the stream is finished and `usage` is populated with the full
/// token accounting for the request.
///
/// Use the constructor helpers ([`stop`](Self::stop), [`content`](Self::content),
/// [`thought`](Self::thought), [`tool_call`](Self::tool_call)) to build chunks
/// without manually zeroing unused fields.
#[derive(Debug, Default, Clone, Serialize, Deserialize)]
pub struct CompletionChunkResponse {

    pub id: String,
    /// Model that generated this chunk (only set on the final chunk).
    pub model: String,
    /// Provider-assigned response ID (only set on the final chunk).
    pub response_id: String,
    /// Incremental visible text for this chunk.
    pub content: String,
    /// Incremental thought / reasoning text for this chunk.
    pub thought: String,
    /// Raw extended-thinking text as returned by the provider.
    pub thinking: String,
    /// `true` on the last chunk of the stream.
    pub is_final: bool,
    /// Token usage populated on the final chunk; `None` for intermediate chunks.
    pub usage: Option<CompletionResponseTokenUsage>,
    /// Set when the model requests a tool call in this chunk.
    pub tool_call: Option<ToolCallRequest>,
}

impl CompletionChunkResponse {
    /// Build a terminal chunk that signals the end of the stream.
    pub fn stop(
        id: String,
        model: String,
        response_id: String,
        usage: Option<CompletionResponseTokenUsage>,
    ) -> CompletionChunkResponse {
        CompletionChunkResponse {
            id,
            model,
            response_id,
            content: String::new(),
            thought: String::new(),
            thinking: String::new(),
            is_final: true,
            usage,
            tool_call: None,
        }
    }

    /// Build a chunk carrying incremental visible content and optional raw thinking text.
    pub fn content(id: String, content: String, thinking: String) -> CompletionChunkResponse {
        CompletionChunkResponse {
            id,
            model: String::new(),
            response_id: String::new(),
            content,
            thought: String::new(),
            thinking,
            is_final: false,
            usage: None,
            tool_call: None,
        }
    }

    /// Build a chunk carrying an incremental chain-of-thought fragment.
    pub fn thought(id: String, thought: String) -> CompletionChunkResponse {
        CompletionChunkResponse {
            id,
            model: String::new(),
            response_id: String::new(),
            content: String::new(),
            thought,
            thinking: String::new(),
            is_final: false,
            usage: None,
            tool_call: None,
        }
    }

    /// Build a chunk representing a tool-call request from the model.
    ///
    /// # Panics
    ///
    /// Panics if any of `id`, `name`, or `arguments` is `None`.
    pub fn tool_call(
        id: String,
        tool_id: Option<String>,
        name: Option<String>,
        arguments: Option<Value>,
    ) -> CompletionChunkResponse {
        CompletionChunkResponse {
            id,
            model: String::new(),
            response_id: String::new(),
            content: String::new(),
            thought: String::new(),
            thinking: String::new(),
            is_final: false,
            usage: None,
            tool_call: Some(ToolCallRequest {
                id: tool_id.unwrap(),
                name: name.unwrap(),
                arguments: arguments.unwrap(),
            }),
        }
    }
}
